version: "3.8"
services:
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: element_store
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
volumes:
  mongodb_data:
